---
name: Release

on:
  push:
    tags: ['*']

env:
  APPNAME: 'appname'
  TARGET_OS: 'linux'
  TARGET_ARCH: 'arm64'
  RELEASE_VERSION: '0.0.0-development'

jobs:
  release:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: get app name
        run: echo "${{ github.REPOSITORY }}" | cut -d / -f2 | awk '{print "APPNAME="$0}' >> $GITHUB_ENV

      - name: get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: set version string
        run: sed -i 's/${{ env.APPNAME }}\/0.0.0/${{ env.APPNAME }}\/${{ github.REF_NAME }}/' backend/main.go

# Build backend
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'

      - name: test backend
        run: |
          cd backend/
          go test ./...

      - name: build backend
        run: |
          cd backend/
          GOOS=${{ env.TARGET_OS }} GOARCH=${{ env.TARGET_ARCH }} CGO_ENABLED=0 go build -o ../${{ env.APPNAME }}/${{ env.APPNAME }}.${{ env.TARGET_ARCH }}

# Build frontend
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: npm ci
        run: |
          cd frontend/
          npm ci

      - name: audit frontend production deps
        run: |
          cd frontend/
          npm run audit:prod

      - name: build frontend
        run: |
          cd frontend/
          npm run build

# Collect and create artifacts for release
      - name: collect and create artifacts
        run: |
          mv frontend/dist/ ${{ env.APPNAME }}/
          tar -czvf ${{ env.APPNAME }}-${{ env.RELEASE_VERSION }}-${{ env.TARGET_ARCH }}.tar.gz ${{ env.APPNAME }}/
          sha256sum ${{ env.APPNAME }}-${{ env.RELEASE_VERSION }}-${{ env.TARGET_ARCH }}.tar.gz > ${{ env.APPNAME }}-${{ env.RELEASE_VERSION }}-${{ env.TARGET_ARCH }}.tar.gz.sha256

      - name: github release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            brave-bpc-${{ env.RELEASE_VERSION}}-${{ env.TARGET_ARCH }}.tar.gz
            brave-bpc-${{ env.RELEASE_VERSION}}-${{ env.TARGET_ARCH }}.tar.gz.sha256

